### PR TITLE
FIX Move Subsite edit permissions column definition into config, now shows at end of list

### LINKED ISSUE #39: Permissions report column for subsites is at the start instead of the end
**Version: CWP 2.2.x-dev**

image

It should be at the RHS end not the LHS

### PR DESCRIPTION
**Pull request by robbieaverill**
Since SilverStripe 4.x, the order of applying extensions and YAML config has changed from SilverStripe 3.x. Moving this config into YAML ensures that the column is appended rather than prepended.

Fixes #39

### CODE REVIEW

File: src/Subsites/SubsiteSecurityReport.php [hunk 1]
```diff
@@ -12,13 +12,4 @@
 class SubsiteSecurityReport extends Extension
 {
 
-    /**
-     * Columns in the report
-     *
-     * @var array
-     * @config
-     */
-    private static $columns = array(
```
Comment (Cheddam) [inline src/Subsites/SubsiteSecurityReport.php]: Should this be removed, if we're only [deprecating the extension](https://github.com/silverstripe/silverstripe-securityreport/pull/41/files) at this stage?

Comment (robbieaverill) [reply src/Subsites/SubsiteSecurityReport.php]: It’s moved into YAML instead

Comment (Cheddam) [reply src/Subsites/SubsiteSecurityReport.php]: Right, and this would be merged up so the deprecation notice applies to a now empty extension - sweet got it 👍
