### PR TITLE
FIX revert removal of 'last logged in' column

### LINKED ISSUE #32: Missing columns in report
The security report no longer contains the columns showing the date and time of the last visit. Were these intentionally removed?

This affects:
 
```
silverstripe/securityreport               dev-master 24a71d6

silverstripe/framework                    4.1.x-dev 9ed3cd4
silverstripe/cms                          4.1.x-dev 7dea009
silverstripe/reports                      4.1.x-dev ac23686
```

Compare against e.g.:

```
silverstripe/securityreport               1.0.10 

silverstripe/framework                    3.6.5   
silverstripe/cms                          3.6.5 
```

### PR DESCRIPTION
**Pull request by NightJar**
This field is gone from member, however we can source the data from
Successful LoginAttempts. As this relies on this data capture to be
enabled, the change also conditionally includes the column, iff the
config setting to log logins is enabled.

Fixes #32

### CODE REVIEW

File: src/MemberReportExtension.php [hunk 1]
```diff
@@ -11,6 +12,16 @@
...
+
+    /**
+     * Connect a link to LoginAttempt
+     * 
+     * @var array
+     * @config
+     */
+    private static $has_many = [
+        'LoginAttempts' => LoginAttempt::class
+    ];
```
Comment (robbieaverill) [inline src/MemberReportExtension.php]: Are we able to achieve this functionality without introducing this new relationship?

Comment (NightJar) [reply src/MemberReportExtension.php]: It's not really a new relationship, rather a reflection of an existing one:
https://github.com/silverstripe/silverstripe-framework/blob/4.1.0/src/Security/LoginAttempt.php#L46

I thought as `has_many` doesn't impact storage at all that this was an acceptable addition.
It can of course be done without it. Would you like me to refactor?

Comment (robbieaverill) [reply src/MemberReportExtension.php]: Oh ok, so that relationship is always there, but whether or not it's active is configurable? If that's the case perhaps you could just leave a comment on that line to point that out

Comment (NightJar) [reply src/MemberReportExtension.php]: Sure :)

File: src/MemberReportExtension.php [hunk 2]
```diff
@@ -23,6 +38,19 @@ class MemberReportExtension extends DataExtension
         'PermissionsDescription' => 'Text'
     );
 
+    /**
+     * Retrieves the most recent successful LoginAttempt
+     */
```
Comment (robbieaverill) [inline src/MemberReportExtension.php]: Can you add a return doc block?

File: src/MemberReportExtension.php [hunk 3]
```diff
@@ -23,6 +38,19 @@ class MemberReportExtension extends DataExtension
...
+    public function getLastLoggedIn()
+    {
+        $lastTime = $this->owner->LoginAttempts()
+            ->filter('Status', 'Success')
+            ->sort('Created', 'DESC')
+            ->first();
+
+        return $lastTime ?: _t(__CLASS__ . '.NEVER', 'never');
```
Comment (robbieaverill) [inline src/MemberReportExtension.php]: I kind of feel like this should be `Never` - also do we need to run the text collector?
